#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Lib

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
vector =np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
x = np.array([1,2,3])
print(x.size)

3


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [34]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vector=np.arange(10,50,1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
vector=np.arange(10,50,1)
vector_inversed=vector[::-1]
print(vector_inversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
mat=np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [22]:
array = [1,2,0,0,4,0]
indices= np.nonzero(array)
indices

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
mat=np.ones(9).reshape(3,3)
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
mat=np.random.random((3,3,3))
mat

array([[[0.59882169, 0.67099213, 0.85132015],
        [0.69448955, 0.03221437, 0.41110241],
        [0.85714418, 0.07025522, 0.60569105]],

       [[0.41099891, 0.16596061, 0.02736694],
        [0.46454547, 0.37490529, 0.79217613],
        [0.3394463 , 0.67181226, 0.81207548]],

       [[0.17994589, 0.02278195, 0.35765853],
        [0.61694328, 0.18623043, 0.90185302],
        [0.83836996, 0.63720384, 0.01233105]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:
mat=np.random.random((10,10))
max,min=mat.max(),mat.min()
print(mat)
print(max)
print(min)

[[0.34533283 0.83387184 0.45247168 0.26544594 0.3410448  0.1420231
  0.94832021 0.55079561 0.33519363 0.82224936]
 [0.81219904 0.87074246 0.98213363 0.39987679 0.76035174 0.33098776
  0.24104821 0.5895735  0.73235654 0.66168119]
 [0.95193168 0.55321995 0.01007662 0.95704489 0.40000799 0.25203049
  0.84289271 0.87702823 0.12986311 0.72906027]
 [0.42774449 0.8566211  0.55815273 0.31085123 0.10578141 0.01691743
  0.62594141 0.34955523 0.13733425 0.55736963]
 [0.83581665 0.94989971 0.63301393 0.01090781 0.38598082 0.37832028
  0.60128002 0.48584546 0.64618344 0.33210644]
 [0.6514864  0.6339492  0.96078523 0.49420656 0.7287985  0.70462128
  0.71004305 0.5924724  0.24732195 0.45638802]
 [0.45805366 0.52495057 0.89573127 0.04903208 0.30358112 0.45374203
  0.27961412 0.75061414 0.32867062 0.30698577]
 [0.52771125 0.55573824 0.70999225 0.95959285 0.74019783 0.70986334
  0.5447115  0.84909079 0.07919049 0.42834446]
 [0.00232411 0.00437493 0.70372515 0.94637901 0.14973583 0.49538078
  0.30423076 

In [ ]:
 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
vector=np.random.random(30)
vector.mean()

0.41406462463913685

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [5]:
array= np.array(([1,0]
               ,[1,0,]))
print(array.ndim)
array

2


array([[1, 0],
       [1, 0]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [56]:
array= np.array(([1,1]
               ,[1,1,]))
border=np.pad(array,pad_width=1)
border

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [58]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [64]:
Z = np.array(([0,0,0,0,0],
 [1,0,0,0,0],
 [0,2,0,0,0],
 [0,0,3,0,0],
 [0,0,0,4,0]))
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [3]:
mat= np.zeros((8,8))
mat[1::2,::2] = 1
mat[::2,1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (search on it )

In [4]:
mat = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix knowing normalization = (x-min/max-min )

In [5]:
mat = np.random.random((5,5))
mat = (mat-np.mean(mat))/(np.std(mat))
print(mat)

[[ 0.28170831  1.30841608 -0.67841965 -0.76934214  0.5164139 ]
 [ 1.20260067  1.30857452  0.94796096 -1.7416972   0.19572477]
 [-1.15019838 -1.65259695  0.36023812 -0.41487403 -0.42817498]
 [ 0.00535657 -0.07117426 -1.15852025  1.14455786 -0.56215677]
 [-0.34279076  1.09204354  1.50466529  0.82964618 -1.7279614 ]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
mat=np.dot(np.ones((5,3)),np.ones((3,2)))
mat

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [13]:
array=np.arange(9)
array[(array >3)&(array <8)] *=-1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\midot\AppData\Local\Temp\ipykernel_22540\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\midot\AppData\Local\Temp\ipykernel_22540\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\midot\AppData\Local\Temp\ipykernel_22540\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
array1=np.arange(11)
array2=np.arange(7,25)
intersect=np.intersect1d(array1,array2)
intersect

array([ 7,  8,  9, 10])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
NO

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [18]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tmrow  = np.datetime64('today') + np.timedelta64(1)
yesterday,today,tmrow

(numpy.datetime64('2024-07-14'),
 numpy.datetime64('2024-07-15'),
 numpy.datetime64('2024-07-16'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [19]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [20]:
a = np.ones(3)*1
b = np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [27]:
array= np.arange(10)
n1= array//1
n2=array -array%1
n3=np.floor(array)
n4=np.trunc(mat)
print(n1,n2,n3,n4)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
mat=np.random.randint(0,4,(5,5))
mat

array([[1, 2, 1, 1, 2],
       [3, 1, 1, 0, 1],
       [3, 1, 3, 3, 3],
       [3, 2, 0, 3, 1],
       [0, 0, 0, 1, 0]])

## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
mat=np.random.randint(0,10,(5,5))
mat

array([[5, 9, 8, 8, 0],
       [6, 2, 7, 1, 5],
       [1, 8, 0, 0, 9],
       [6, 3, 5, 8, 6],
       [7, 4, 1, 2, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
vector = np.linspace(0,1,11,endpoint=False)[1:]
print(vector)
vector.sort()
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
array = np.arange(10)
sum=np.add.reduce(array)
print(sum)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
array1=np.arange(11)
array2=np.arange(7,25)
check=np.array_equal(array1,array2)
print(check)

False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [57]:
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)


[0.01711803 0.0529786  0.17145075 0.14977494 0.50666552 0.23574791
 0.86408828 0.42928441 0.         0.94962689]


#### 49. How to print all the values of an array? (★★☆)

In [63]:
np.set_printoptions(threshold=int("5"))
values = np.ones((40,40))
print(values)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [65]:
vector = np.arange(100)
value = np.random.uniform(0,100)
index = (np.abs(vector-value)).argmin()
print(vector[index])

1
